---
# In the PAGoDA context, there is no need to define the underlying Persistent
# Volume of the following PVC. This is because the the PV will be automagically
# created by the platform (FIXME: document the mechanism).
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vcity-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-rbd
